import type { CodegenConfig } from '@graphql-codegen/cli';

/**
 * Generates TypeScript types and typed operation documents from the authoritative
 * schema in ../../graphql. Output is git-ignored and regenerated by
 * `pnpm run codegen` (or `make generate-ui` from the repository root), matching how
 * ui/v2.5 treats its own generated GraphQL.
 *
 * `documentMode: 'string'` emits operations as plain strings rather than parsed
 * DocumentNodes, so the `graphql` package stays a build-time dependency and never
 * reaches the browser bundle.
 */
const config: CodegenConfig = {
	schema: '../../graphql/schema/**/*.graphql',
	documents: 'src/lib/api/documents/**/*.graphql',
	ignoreNoDocuments: true,
	generates: {
		'src/lib/api/generated/': {
			preset: 'client',
			presetConfig: {
				fragmentMasking: false
			},
			config: {
				documentMode: 'string',
				strictScalars: true,
				// tsconfig sets verbatimModuleSyntax, which rejects type-only symbols
				// imported as values. Fixed here rather than in the output, which is
				// generator-owned.
				useTypeImports: true,
				// The Go server's custom scalars. strictScalars fails the build if one
				// is added upstream without a mapping here, rather than silently
				// typing it as `any`.
				scalars: {
					Time: 'string',
					Timestamp: 'string',
					Map: '{ [key: string]: unknown }',
					BoolMap: '{ [key: string]: boolean }',
					PluginConfigMap: '{ [id: string]: { [key: string]: unknown } }',
					Any: 'unknown',
					Int64: 'number',
					Upload: 'File'
				}
			}
		}
	}
};

export default config;
